name: Push to GitHub Repository
description: Push the generated project to the new GitHub repository

inputs:
  name:
    description: 'Repository Name'
    required: true
  userEmail:
    description: 'User Email'
    required: true
  userName:
    description: 'User Name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Push to new repository
      run: |
        cd spring-boot-project
        echo "# ${{ inputs.name }}" >> README.md
        git config --global user.email "${{ inputs.userEmail }}"
        git config --global user.name "${{ inputs.userName }}"
        git init
        git add .
        git add README.md
        git commit -m "first commit"
        git branch -M main
        git remote add origin git@github.com:${{ github.actor }}/${{ inputs.name }}.git
        git remote set-url origin https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.actor }}/${{ inputs.name }}
        git push -u origin main  # Push to 'main' branch
