name: Create Spring Boot Repository

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repository Name'
        required: true
      description:
        description: 'Repository Description'
        required: true
      private:
        description: 'Private Repository'
        required: true
        default: 'false'
      groupId:
        description: 'Maven Group ID'
        required: true
      artifactId:
        description: 'Maven Artifact ID'
        required: true
      springBootVersion:
        description: 'Spring Boot Version'
        required: true
        default: '3.0.0'
      mainClassName:
        description: 'Main Class Name'
        required: true
        default: 'Application'
      userName:
        description: 'User Name'
        required: true
      userEmail:
        description: 'User Email'
        required: true
        
jobs:
  create-spring-boot-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: ../.github/actions/checkout-code

    - name: Step 2 - Generate Spring Boot Project with Maven Wrapper
      uses: ../.github/actions/generate-spring-boot-project
      with:
        springBootVersion: ${{ github.event.inputs.springBootVersion }}
        groupId: ${{ github.event.inputs.groupId }}
        artifactId: ${{ github.event.inputs.artifactId }}
        mainClassName: ${{ github.event.inputs.mainClassName }}

    - name: Step 3 - Create new GitHub repository
      uses: ../.github/actions/create-github-repo
      with:
        name: ${{ github.event.inputs.name }}
        description: ${{ github.event.inputs.description }}
        private: ${{ github.event.inputs.private }}

    - name: Step 4 - Push to new repository
      uses: ../.github/actions/push-to-github-repo
      with:
        name: ${{ github.event.inputs.name }}
        userEmail: ${{ github.event.inputs.userEmail }}
        userName: ${{ github.event.inputs.userName }}
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
